"""create users table

Revision ID: 6b8025cd418e
Revises: 
Create Date: 2026-03-19 22:09:17.456541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic.
revision: str = '6b8025cd418e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Commands autogenerated by Alembic; adjust if needed.
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('buyer', 'seller', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # End Alembic commands.


def downgrade() -> None:
    """Downgrade schema."""
    # Commands autogenerated by Alembic; adjust if needed.
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # End Alembic commands.
