"""create users table

Revision ID: a39af2b753a0
Revises: 6b8025cd418e
Create Date: 2026-03-20 11:17:26.338623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic.
revision: str = 'a39af2b753a0'
down_revision: Union[str, Sequence[str], None] = '6b8025cd418e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Commands autogenerated by Alembic; adjust if needed.
    pass
    # End Alembic commands.


def downgrade() -> None:
    """Downgrade schema."""
    # Commands autogenerated by Alembic; adjust if needed.
    pass
    # End Alembic commands.
